services:
  frontback:
    build:
      context: .
      dockerfile: Dockerfile.frontback
    container_name: frontback
    ports:
      - "8080:8080"
    environment:
      - JVM_OPTS=-Xms512m -Xmx1G
      - server_host=0.0.0.0
      - server_port=8080
      - otel_host=collector
      - otel_port=4318
    restart: unless-stopped
  collector:
    image: "otel/opentelemetry-collector-contrib@sha256:e39311df1f3d941923c00da79ac7ba6269124a870ee87e3c3ad24d60f8aee4d2"
    volumes:
      - ./collector.yaml:/etc/otel/collector.yaml
    entrypoint: ["/otelcol-contrib"]
    command: ["--config", "/etc/otel/collector.yaml"]
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
  jaeger:
    image: "jaegertracing/all-in-one:1.60@sha256:4fd2d70fa347d6a47e79fcb06b1c177e6079f92cba88b083153d56263082135e"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - COLLECTOR_OTLP_HTTP_HOST_PORT=0.0.0.0:4318
    ports:
      - "16686:16686" # UI