services:
  authorization:
    build:
      context: .. # откуда нюхать файлы
      dockerfile: docker/Dockerfile.authorization # путь докерфайла также учитывает контекст
    container_name: authorization
    ports:
      - "8081:8081"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8081
      - AUTH_KEY=k9EwzXH4QZkz2qZ8QfP4aK8xN0mH2vY8d7mF3B2cL6o=
      - AUTH_ISSUER=auth_pod1
      - OTEL_HOST=0.0.0.0
      - OTEL_PORT=4317
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - JVM_OPTS=-Xms512m -Xmx1G
      - server_host=0.0.0.0
      - server_port=8080
      - otel_host=collector
      - otel_port=4318
      - auth_host=0.0.0.0
      - auth_port=8081
    restart: unless-stopped
  collector:
    image: "otel/opentelemetry-collector-contrib@sha256:e39311df1f3d941923c00da79ac7ba6269124a870ee87e3c3ad24d60f8aee4d2"
    volumes:
      - ./collector.yaml:/etc/otel/collector.yaml
    entrypoint: ["/otelcol-contrib"]
    command: ["--config", "/etc/otel/collector.yaml"]
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
  jaeger:
    image: "jaegertracing/all-in-one:1.60@sha256:4fd2d70fa347d6a47e79fcb06b1c177e6079f92cba88b083153d56263082135e"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - COLLECTOR_OTLP_HTTP_HOST_PORT=0.0.0.0:4318
    ports:
      - "16686:16686" # UI